### ISSUE TITLE
Items have attribute 'wiedable' instead of 'wieldable' - spelling mistake ?

### ISSUE THREAD

**Issue by techcobweb** [chrisesharp/roguelike#17]
Unfortunately, this is visible to clients over the web socket also.

**Comment by techcobweb** [comment]
Looks like this is fixed in the TS version now.

**Comment by techcobweb** [comment]
Need the 'W' (upper-case) added to the list of supported keys in the README.

**Comment by chrisesharp** [comment]
Added now
