### ISSUE TITLE
A dead bot can pick up it's own body !

### ISSUE THREAD

**Issue by techcobweb** [chrisesharp/roguelike#22]
This made me chuckle. Not having implemented detection of my own death, I slowed the bot movement down so I could beat it up with a manually-controlled player.
```
Server                                Bot
-------->DEAD---------> ignore
-------->Items update--> there is now a body object where I'm standing
…time passes…
       <----------------- pick up the body, as it's where I am.
-------->items update---> there is no body there now. (as I have picked it up successfully)
```

**Comment by techcobweb** [comment]
implemented death now so not seeing this any longer, as the DEAD event causes the client to exit cleanly.

**Comment by chrisesharp** [comment]
It's a fair point, though...the server should ignore any requests to do anything from a dead entity.

**Comment by chrisesharp** [comment]
Added now.
