### ISSUE TITLE
Some dungeons have rooms with items inside, but no way to get into that room.

### ISSUE THREAD

**Issue by techcobweb** [chrisesharp/roguelike#26]
eg:
```
######X   ##       ##########     ######
#####..            #####################
#### <             ##################  #
#####              ##########  #####  * 
######              ########    ###     
#########             #####     ###    #
##########             ####    ####   ##
#########             ####<    ####   ##
#######              #####    ####    ##
###                 ######   #####    ##
##                  ###############  ###
##                 #####################
##                #####< ###############
```

The '*' on the right is the item in the unreachable room.
X is the bot.

So it looks like the map generation has a bug gin somewhere, as this shouldn't happen.

I note there is no wall on the far right, so maybe it intended to put stairs there, but the width is out by 1 or something ?

**Comment by chrisesharp** [comment]
Added digging support AND put a granite seal around the whole map to prevent those open ended caves. This should eliminate this problem.
