### ISSUE TITLE
The server reset shouldn't be on a get, but on a PUT ?

### ISSUE THREAD

**Issue by techcobweb** [chrisesharp/roguelike#9]
Resetting the server using an HTTP GET command seems wrong to me.
I know it's convenient, but changing the server state violates the read-only nature by adding a side-effect.

If this gets changed, then the README.md may also need changing, or wherever the current HTTP API is documented/defined.

**Comment by chrisesharp** [comment]
This is probably correct. I'm not entirely happy with a reset api anyway, though. It's largely there for testing :-(

**Comment by chrisesharp** [comment]
Agree..changed it now. Ofcourse, we ultimately need auth implented!
